openapi: 3.0.0
info:
  version: 1.0.0.alpha-3
  title: VAE_V2X_Message_Delivery
  description: VAE V2X Message Delivery Service
security:
  - {}
  - oAuth2ClientCredentials: []
externalDocs:
  description: 3GPP TS 29.486 V0.3.0 V2X Application Enabler (VAE) Services
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.486/'
servers:
  - url: '{apiRoot}/vae-v2x-message-delivery/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501
paths:
  /message-deliveries:
    post:
      summary: VAE V2X Message delivery resource create service Operation
      tags:
        - message deliveries collection (Document)
      operationId: CreateMessageDelivery
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V2xMessageDeliveryData'
        required: true
      responses:
        '201':
          description: Message Delivery Resource Created
          headers:
            Location:
              description: 'Contains the URI of the newly created resource, according to the structure: {apiRoot}/vae-v2x-message-delivery/v1/message-deliveries/{deliveryId}'
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V2xMessageDeliveryData'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '411':
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
  /message-deliveries/{deliveryId}:
    get:
      parameters:
        - name: deliveryId
          in: path
          description: Identifier of a messge delivery resource
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK. Resource representation is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V2xMessageDeliveryData'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29571_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29571_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'
    delete:
      summary: VAE V2X Message delivery resource delete service Operation
      tags:
        - Individual message delivery (Document)
      operationId: DeleteMessageDelivery
      parameters:
        - name: deliveryId
          in: path
          required: true
          description: Unique ID of the message delivery to be deleted
          schema:
            type: string
      responses:
        '200':
          description: message delivery resource deleted successfully
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows: 
        clientCredentials: 
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            vae-v2x-message-delivery: Access to the VAE_V2X_Message_Delivery API
  schemas:
    V2xMessageDeliveryData:
      type: object
      properties:
        ueId:
          $ref: '#/components/schemas/V2xUeId'
        groupId:
          $ref: '#/components/schemas/V2xGroupId'
        duration:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DateTime'
        serviceId:
          $ref: '#/components/schemas/V2xServiceId'
        geoId:
          $ref: '#/components/schemas/GeoId'
        payload:
          $ref: '#/components/schemas/V2xMessagePayload'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
    V2xUeId:
      type: string
    V2xGroupId:
      type: string
    V2xServiceId:
      type: string
    GeoId:
      type: string
    V2xMessagePayload:
      $ref: 'TS29571_CommonData.yaml#/components/schemas/Bytes'
