openapi: 3.0.0

info:
  version: '1.0.0.alpha-1'
  title: 'Nhss_UECM'
  description: |
    HSS UE Context Management
    © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.563 Home Subscriber Server (HSS)Services for Interworking With UDM, version 0.4.0
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.563/'

servers:
  - url: '{apiRoot}/nhss-uecm/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

security:
  - oAuth2ClientCredentials:
    - nhss-uecm
  - {}

paths:
  /deregister-mme:
    post:
      summary: MME Deregistration
      operationId: Deregister MME
      tags:
        - MME Deregistration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeregistrationRequest'
        required: true
      responses:
        '204':
          description: No content
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '501':
          $ref: 'TS29571_CommonData.yaml#/components/responses/501'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows: 
        clientCredentials: 
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nhss-uecm: Access to the nhss-uecm API

  schemas:

# COMPLEX TYPES:

    DeregistrationRequest:
      type: object
      required:
        - imsi
        - deregReason
      properties:
        imsi:
          type: string
          pattern: '^[0-9]{5,15}$'
        deregReason:
          $ref: '#/components/schemas/DeregistrationReason'

# SIMPLE TYPES:


# ENUMS:

    DeregistrationReason:
      anyOf:
        - type: string
          enum:
            - UE_INITIAL_REGISTRATION
            - EPS_TO_5GS_MOBILITY
        - type: string  
