openapi: 3.0.0
info:
  version: 1.1.0.alpha-2
  title: Nnwdaf_AnalyticsInfo
  description: |
    Nnwdaf_AnalyticsInfo Service API.
    © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: 3GPP TS 29.520 V16.2.0; 5G System; Network Data Analytics Services.
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.520/'
security:
  - {}
  - oAuth2ClientCredentials:
    - nnwdaf-analyticsinfo
servers:
  - url: '{apiRoot}/nnwdaf-analyticsinfo/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501.
paths:
  /analytics:
    get:
      parameters:
        - name: event-id
          in: query
          description: Identify the analytics.
          required: true
          schema:
            $ref: '#/components/schemas/EventId'
        - name: ana-req
          in: query
          description: Identifies the analytics reporting requirement information.
          required: false
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyticsReportingRequirement'
        - name: event-filter
          in: query
          description: Identify the analytics.
          required: false
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventFilter'
        - name: supported-features
          in: query
          description: To filter irrelevant responses related to unsupported features
          schema:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
        - name: tgt-ue
          in: query
          description: Identify the target UE information.
          required: false
          content:
            application/json:
              schema:
                $ref: 'TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/TargetUeInformation'
      responses:
        '200':
          description: Containing the analytics with parameters as relevant for the requesting NF service consumer.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyticsData'
        '204':
          description: No Content (The request NWDAF Analytics data does not exist)
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29571_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          description: Indicates that the NWDAF Analytics resource does not exist.
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '406':
          $ref: 'TS29571_CommonData.yaml#/components/responses/406'
        '414':
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nnwdaf-analyticsinfo: Access to the Nnwdaf_AnalyticsInfo API
  schemas:
    AnalyticsData:
      type: object
      properties:
        sliceLoadLevelInfos:
          type: array
          items:
            $ref: 'TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/SliceLoadLevelInformation'
          minItems: 1
          description: The slices and their load level information.
        networkPerfs:
          type: array
          items:
            $ref: '#/components/schemas/NetworkPerformanceInfo'
          minItems: 1
        svcExpInfo:
          type: string
        qosSustainInfo:
          type: array
          items:
            $ref: 'TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/QosSustainabilityInfo'
          minItems: 1
        ueMobs:
          type: array
          items:
            $ref: 'TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/UeMobility'
          minItems: 1
        ueComms:
          type: array
          items:
            $ref: 'TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/UeCommunication'
          minItems: 1
        userDataCongInfos:
          type: array
          items:
            $ref: 'TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/UserDataCongestionInfo'
          minItems: 1
        abnorBehavrs:
          type: array
          items:
            $ref: 'TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/AbnormalBehaviour'
          minItems: 1

    EventFilter:
      type: object
      properties:
        anySlice:
          $ref: 'TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/AnySlice'
        snssais:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Snssai'
          minItems: 1
          description: Identification(s) of network slice to which the subscription belongs.
        appIds:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/ApplicationId'
          minItems: 1
        dnns:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnn'
          minItems: 1
        dnais:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnai'
          minItems: 1
        networkArea:
          $ref: 'TS29554_Npcf_BDTPolicyControl.yaml#/components/schemas/NetworkAreaInfo'
        maxAnaEntry:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uinteger'
        qosRequ:
          $ref: 'TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/QosRequirement'
        qosFlowRetainThresholds:
          type: array
          items:
            $ref: 'TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/ThresholdLevel'
          minItems: 1
        ranUeThroughputThresholds:
          type: array
          items:
            $ref: 'TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/ThresholdLevel'
          minItems: 1
        not:
          required: [anySlice, snssais]
    AnalyticsReportingRequirement:
      type: object
      properties:
        accuracy:
          $ref: 'TS29520_Nnwdaf_EventsSubscription.yaml#/components/schemas/Accuracy'
        startTs:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DateTime'
        endTs:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DateTime'
        sampRatio:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uinteger'
    NetworkPerformanceInfo:
      type: string
# Editor's note: The data type NetworkPerformanceInfo is FFS.
    EventId:
      anyOf:
      - type: string
        enum:
          - LOAD_LEVEL_INFORMATION
          - SERVICE_EXPERIENCE
          - QOS_SUSTAINABILITY
          - ABNORMAL_BEHAVIOUR
          - USER_DATA_CONGESTION
      - type: string
        description: >
          This string provides forward-compatibility with future
          extensions to the enumeration but is not used to encode
          content defined in the present version of this API.
      description: >
        Possible values are
        - LOAD_LEVEL_INFORMATION: Represent the analytics of load level information of corresponding network slice instance.
        - SERVICE_EXPERIENCE: Represent the analytics of service experience information of the specific applications.
        - QOS_SUSTAINABILITY: Represent the analytics of QoS sustainability information in the certian area. 
        - ABNORMAL_BEHAVIOUR: Indicates that the event subscribed is abnormal behaviour information.
        - USER_DATA_CONGESTION: Represent the analytics of the user data congestion in the certain area.
