openapi: 3.0.0

info:
  version: '1.0.0.alpha-1'
  title: 'Nhss_imsSDM'
  description: |
    Nhss Subscriber Data Management Service for IMS.
    © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.562 Unified Data Management Services, version 0.3.0
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.562/'

servers:
  - url: '{apiRoot}/nhss-ims-sdm/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

security:
  - oAuth2ClientCredentials:
    - nhss-ims-sdm
  - {}

paths:
  /{imsUeId}/ims-data/location-data/scscf-capabilities:
    get:
      summary: Retrieve the S-CSCF capabilities for the associated IMS subscription
      operationId: GetScscfCapabilities
      tags:
        - Retrieval of the S-CSCF capabilities for the IMS subscription
      parameters:
        - name: imsUeId
          in: path
          description: IMS Identity
          required: true
          schema:
            $ref: '#/components/schemas/ImsUeId'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScscfCapabilityList'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '405':
          $ref: 'TS29571_CommonData.yaml#/components/responses/405'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        '504':
          $ref: 'TS29571_CommonData.yaml#/components/responses/504'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /{imsUeId}/repository-data/{serviceIndication}:
    get:
      summary: Retrieve the repository data associated to an IMPU and service indication
      operationId: GetRepositoryDataServInd
      tags:
        - Repository data
      parameters:
        - name: imsUeId
          in: path
          description: IMS Identity
          required: true
          schema:
            $ref: '#/components/schemas/ImsUeId'
        - name: serviceIndication
          in: path
          description: Identifier of a service related data
          required: true
          schema:
            $ref: '#/components/schemas/ServiceIndication'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoryData'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '405':
          $ref: 'TS29571_CommonData.yaml#/components/responses/405'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /{imsUeId}/identities/msisdns:
    get:
      summary: retrieve the Msisdns associated to requested identity
      operationId: GetMsisdns
      tags:
        - Retrieval of the associated Msisdns 
      parameters:
        - name: imsUeId
          in: path
          description: IMS Identity
          required: true
          schema:
            $ref: '#/components/schemas/ImsUeId'
        - name: privateId
          in: query
          description: Private identity
          schema:
            $ref: '#/components/schemas/PrivateId'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsisdnList'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '405':
          $ref: 'TS29571_CommonData.yaml#/components/responses/405'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /{imsUeId}/identities/ims-associated-identities:
    get:
      summary: Retrieve the associated identities to the IMS public identity included in the service request
      operationId: GetImsAssocIds
      tags:
        - Retrieval of associated IMS public identities
      parameters:
        - name: imsUeId
          in: path
          description: IMS Public Identity
          required: true
          schema:
            $ref: '#/components/schemas/ImsUeId'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicIdentities'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '405':
          $ref: 'TS29571_CommonData.yaml#/components/responses/405'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

components:
  schemas:

# COMPLEX TYPES:

    ScscfCapabilityList:
      type: object
      properties:
        mandatoryCapabilityList:
          $ref: '#/components/schemas/Capabilities'
        optionalCapabilityList:
          $ref: '#/components/schemas/Capabilities'
      anyOf:
       - required: [mandatoryCapabilityList]
       - required: [optionalCapabilityList]

    Capabilities:
      type: array
      items:
        $ref: '#/components/schemas/Capability'
      minItems: 1
      uniqueItems: true

    RepositoryData:
      type: object
      required:
        - serviceData
        - sequenceNumber
      properties:
        sequenceNumber:
            $ref: '#/components/schemas/SequenceNumber'
        serviceData:
          type: string
          format: byte

    MsisdnList:
      type: object
      required:
        - basicMsisdn
      properties:
        basicMsisdn:
            $ref: '#/components/schemas/Msisdn'
        additionalMsisdns:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Msisdn'

    PublicIdentities:
      type: object
      required:
       - publicIdentities
      properties:
        publicIdentities:
          type: array
          items:
            $ref: '#/components/schemas/PublicIdentity'
          minItems: 1
          uniqueItems: true

    PublicIdentity:
      type: object
      required:
        - imsPublicId
        - identityType
      properties:
        imsPublicId:
          $ref: '#/components/schemas/ImsPublicId'
        identityType:
          $ref: '#/components/schemas/IdentityType'
        irsIsDefault:
          type: boolean
        aliasGroupId:
          type: integer

# SIMPLE TYPES:

    Capability:
      type: integer

    ImsUeId:
      type: string
      pattern: '^sip\:([a-zA-Z0-9_\-.!~*()&=+$,;?\/]+)\@([A-Za-z0-9]+([-A-Za-z0-9]+)\.)+[a-z]{2,}$|^tel\:\+[0-9]{5,15}$'

    SequenceNumber:
      type: integer
      minimum: 0

    ServiceIndication:
      type: string

    Msisdn:
      type: string
      pattern: '[0-9]{5,15}$'

    PrivateId:
      type: string

    ImsPublicId:
      type: string
      pattern: '^(sip\:([a-zA-Z0-9_\-.!~*()&=+$,;?\/]+)\@([A-Za-z0-9]+([-A-Za-z0-9]+)\.)+[a-z]{2,}|tel\:\+[0-9]{5,15})$'

# ENUMS:

    IdentityType:
      anyOf:
        - type: string
          enum:
          - DISTINCT_IMPU
          - DISTINCT_PSI
          - WILDCARDED_IMPU
          - WILDCARDED_PSI
        - type: string
