openapi: 3.0.0

info:
  version: '1.0.0.alpha-1'
  title: 'Nhss_imsUECM'
  description: |
    Nhss Subscriber Data Management Service for IMS.
    © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.562 Unified Data Management Services, version 0.3.0
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.562/'

servers:
  - url: '{apiRoot}/nhss-ims-uecm/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

security:
  - oAuth2ClientCredentials:
    - nhss-ims-uecm
  - {}

paths:

  /{impu}/authorize:
    post:
      summary: Authorize IMS Identities to register in the network or establish multimedia sessions and return CSCF location if it is stored 
      operationId: Authorize
      tags:
        - Authorize Ims identities
      parameters:
        - name: impu
          in: path
          description: Public identity of the user. 
          required: true
          schema:
              $ref: '#/components/schemas/Impu'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizationRequest'
        required: true
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        default:
          description: Unexpected error

components:

  schemas:

# COMPLEX TYPES:

    AuthorizationRequest:
      description: Ims authorization request data
      type: object
      required:
        - authorizationType
      properties:
        impi:
          $ref: '#/components/schemas/Impi'
        authorizationType:
          description: authorization type
          $ref: '#/components/schemas/AuthorizationType'
        visitedNetworkIdentifier:
          type: string
        emergencyIndicator:
          type: boolean
        supportedFeatures:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'

    AuthorizationResponse:
      description: Ims Registration authorization information result
      type: object
      properties:
        authorizationResult:
          $ref: '#/components/schemas/AuthorizationResult'
        cscfServerName:
          type: string
        
# SIMPLE TYPES

    Impu:
      type: string
    Impi:
      type: string

# ENUMS:

    AuthorizationType:
      anyOf:
        - type: string
          enum:
          - REGISTRATION
          - DEREGISTRATION
        - type: string

    AuthorizationResult:
      anyOf:
        - type: string
          enum:
          - FIRST_REGISTRATION
          - SUBSEQUENT_REGISTRATION
        - type: string
