openapi: 3.0.0

info:
  version: '1.0.0.alpha-1'
  title: 'Nhss_SDM'
  description: |
    HSS Subscriber Data Management.
    © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.563 Home Subscriber Server (HSS)Services for Interworking With UDM, version 0.4.0
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.563/'

servers:
  - url: '{apiRoot}/nhss-sdm/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

security:
  - oAuth2ClientCredentials:
    - nhss-sdm
  - {}

paths:
  /{ueId}/ue-context-in-pgw-data:
    get:
      summary: Retrieve the UE Context In PGW
      operationId: GetUeCtxInPgwData
      tags:
        - UE Context In PGW Data Retrieval
      parameters:
        - name: ueId
          in: path
          description: Identifier of the UE
          required: true
          schema:
            type: string
            pattern: '^(imsi-[0-9]{5,15})$'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UeContextInPgwData'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error


components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows: 
        clientCredentials: 
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nhss-sdm: Access to the nhss-sdm API


  schemas:

# COMPLEX TYPES:

    UeContextInPgwData:
      type: object
      properties:
        pgwInfo:
          type: array
          items:
            $ref: 'TS29503_Nudm_SDM.yaml#/components/schemas/PgwInfo'
          minItems: 1



# SIMPLE TYPES:


# ENUMS:
